# stats available at
# https://travis-ci.org/fancycode/pylzma
language: python
sudo: false

matrix:
  include:
    - os: linux
      python: 2.6
    - os: linux
      python: 2.7
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5-dev
    - os: linux
      python: nightly
    - os: osx
      language: generic
      env: PYVER=2
    - os: osx
      language: generic
      env: PYVER=3

env:
  - CC=/usr/lib/ccache/gcc CXX=/usr/lib/ccache/g++

addons:
  apt:
    packages:
    - ccache

cache:
  directories:
    - $HOME/.ccache
    - $HOME/.downloads

install:
  - ./scripts/ci-install.sh

script: 
  - python$PYVER setup.py test
